#include <iostream>
#include <cstdlib>
#include <string>
#include <cstring>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <poll.h>
#include <fcntl.h>
#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>
#include <netinet/ip.h>
#include <vector>


static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

static void fd_set_nb(int fd) {
    errno = 0;
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error");
        return;
    }

    flags |= O_NONBLOCK;

    errno = 0;
    (void)fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error");
    }
}

const size_t k_max_msg = 32 << 20;  // likely larger than the kernel buffer

struct Conn {
    int fd = -1;
    // application's intention, for the event loop
    bool want_read = false;
    bool want_write = false;
    bool want_close = false;
    // buffered input and output
    std::vector<uint8_t> incoming;  // data to be parsed by the application
    std::vector<uint8_t> outgoing;  // responses generated by the application
};

//TODO :
// Write a buf conusme
// Write buf append
// handle_read using recv
// handle_write using send
// what protocol to use for this?
//
static void bufconsume(std::vector<uint8_t> &buf, size_t n) {
    buf.erase(buf.begin(), buf.begin() + n);
}

static void bufappend(std::vector<uint8_t> &buf, const char *data, size_t len) {
    buf.insert(buf.end(), data, data + len);
}

static void handle_write(Conn *conn){
    errno = 0; // flush out errno

    while(true){
        ssize_t rv = send(conn->fd, conn->outgoing.data(), conn->outgoing.size(), 0);


        if(rv < 0 && errno == EAGAIN){
            break; // not ready yet
        }
        if( rv < 0 && errno == EINTR){
            continue;
        }

        if (rv < 0){
            msg_errno("send error");
            return;
        }


        bufconsume(conn->outgoing, (size_t)rv); // add the recieved bytes to the conn read buffer
        if (conn->outgoing.size() == 0) {   // all data written
                conn->want_read = true;
                conn->want_write = false;
                break;
        }
    }

}

static void handle_read(Conn *conn){
    errno = 0; // flush out errno
    // read data
    char buffer[64 * 1024];
    while(true){
        int rv = recv(conn->fd, buffer, sizeof(buffer), 0);


        if(rv < 0 && errno == EAGAIN){
            break; // not ready yet
        }
        if( rv < 0 && errno == EINTR){
            continue;
        }

        if (rv < 0){
            msg_errno("recv error");
            return;
        }

        if (rv == 0) {
                if (conn->incoming.size() == 0) {
                    msg("client closed");
                } else {
                    msg("unexpected EOF");
                }
                conn->want_close = true;
                return; // want close
        }
        bufappend(conn->incoming, buffer, (size_t)rv); // add the recieved bytes to the conn read buffer
    }

    while(try_one_request()){} // clients might send multiple messages together (pipelining)

    if(conn->outgoing.size() > 0){
        conn->want_read = false;
        conn->want_write = true;
        return handle_write(conn);
    }

}






static Conn *handle_accept(int fd) {

    struct sockaddr_in client_addr;
    socklen_t client_addr_len = sizeof(client_addr);

    int connfd = accept(fd, (struct sockaddr *) &client_addr, &client_addr_len);

    if (connfd < 0) {
            msg_errno("accept() error");
            return NULL;
    }

    uint32_t ip = client_addr.sin_addr.s_addr;

    fd_set_nb(connfd);

    Conn *conn = new Conn;
    conn->fd = connfd;
    conn->want_read = true;
    return conn;


}

int main(int argc, char **argv) {
  // Flush after every std::cout / std::cerr
  std::cout << std::unitbuf;
  std::cerr << std::unitbuf;

  int server_fd = socket(AF_INET, SOCK_STREAM, 0);
  if (server_fd < 0) {
   std::cerr << "Failed to create server socket\n";
   return 1;
  }

  int reuse = 1;
  if (setsockopt(server_fd, SOL_SOCKET, SO_REUSEADDR, &reuse, sizeof(reuse)) < 0) {
    std::cerr << "setsockopt failed\n";
    return 1;
  }

  struct sockaddr_in server_addr;
  server_addr.sin_family = AF_INET;
  server_addr.sin_addr.s_addr = INADDR_ANY;
  server_addr.sin_port = htons(6379);

  if (bind(server_fd, (struct sockaddr *) &server_addr, sizeof(server_addr)) != 0) {
    std::cerr << "Failed to bind to port 6379\n";
    return 1;
  }

  int connection_backlog = 5;
  if (listen(server_fd, connection_backlog) != 0) {
    std::cerr << "listen failed\n";
    return 1;
  }

  struct sockaddr_in client_addr;
  int client_addr_len = sizeof(client_addr);
  std::cout << "Waiting for clients to connect...\n";

  std::vector<struct pollfd> poll_args;
  std::vector<Conn *> fd2conn;


  while (true){
      poll_args.clear(); //reset the loop on every iteration
      struct pollfd pfd = {server_fd, POLLIN, 0}; // create the listening sockets pollfd struct
      poll_args.push_back(pfd);

    for (Conn *conn : fd2conn) {
        if(!conn){
              continue; // go to next fd
        }

        struct pollfd pfd = {conn->fd, 0, 0};

        if(conn->want_read){
              pfd.events |= POLLIN;
        }

        if(conn->want_write){
              pfd.events |= POLLOUT;
        }

          poll_args.push_back(pfd);
    }

      reuse = poll(poll_args.data(),(nfds_t)poll_args.size(), -1);

    if (reuse < 0 && errno == EINTR){
        continue; // No error occured build the polled fds vector again
    }

    if (reuse < 0){
        die("poll");
    }

    if(poll_args[0].revents){
        if(Conn *conn = handle_accept(server_fd)){
            if(fd2conn.size() <=(size_t)conn->fd){
                fd2conn.resize(conn->fd + 1);
            }
            assert(!fd2conn[conn->fd]);
            fd2conn[conn->fd] = conn;
        }
    }

    for (size_t i = 1; i < poll_args.size(); ++i) { // note: skip the 1st
        uint32_t ready = poll_args[i].revents;

        if (ready == 0) {
            continue;
        }

        Conn *conn = fd2conn[poll_args[i].fd];
        if(ready & POLLIN){
            assert(conn->want_read);
            handle_read(conn);
        }
        if( ready & POLLOUT){
            assert(conn->want_write);
            handle_write(conn);
        }

        if(ready & POLLERR ||conn->want_close){
            fd2conn[poll_args[i].fd] = NULL;
            close(poll_args[i].fd);
            delete conn;
        }
    }

  }


  return 0;
}


// What does accept new conn have to do?
//
// call accept
// handle the error
// set flags?
// put into the array?
